CREATE TABLE IF NOT EXISTS DOCTORS(
id BIGINT NOT NULL,
name VARCHAR(20) NOT NULL,
surname VARCHAR(30) NOT NULL,
second_name VARCHAR(30) NOT NULL,
specialization VARCHAR(60) NOT NULL,
PRIMARY KEY(id)
);
